[package]
name = "color-quantizer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
eframe = "0.29.1"
egui = "0.29.1"
image = "0.25.5"
lru = "0.12.5"
rand = "0.8.5"
rayon = "1.10.0"
rfd = "0.15.1"
strum = "0.26"
strum_macros = "0.26"
